config/routes.rb
Stopricstra::Application.routes.draw do
  resources :messagetolds

  get "welcome/play" => "game#show"
  root :to => "game#show"
  get "game/show" => "game#show"
  get "blog" => "blog#index"
  get "blog/show" => "blog#show"
  post "blog/asdasd" => "blog#dadadasad"
end

app/models/bolgpost.rb
class Bolgpost < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :node
  has_many	:comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :bolgpost
end

app/models/messagetold.rb
class Messagetold < ActiveRecord::Base
  attr_accessible :msg, :user
end

app/models/node.rb
class Node < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :bolgposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index 
    @nodebolgpost = Node.limit(5).all
    respond_to do |format|
      format.html
    #  format.json {render json:@blogpost}
    end
  end

  def show
    @blogpost = Bolgpost.find(params[:id])
    @comments = @blogpost.comments.limit(5).all
    respond_to do |format|
      format.json {render :json => {:blogpost => @blogpost,
                          :comments => @comments}}

    end 
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def show 
  end
end

app/controllers/messagetolds_controller.rb
class MessagetoldsController < ApplicationController
  # GET /messagetolds
  # GET /messagetolds.json
  def index
    @messagetolds = Messagetold.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messagetolds }
    end
  end

  # GET /messagetolds/1
  # GET /messagetolds/1.json
  def show
    @messagetold = Messagetold.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @messagetold }
    end
  end

  # GET /messagetolds/new
  # GET /messagetolds/new.json
  def new
    @messagetold = Messagetold.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @messagetold }
    end
  end

  # GET /messagetolds/1/edit
  def edit
    @messagetold = Messagetold.find(params[:id])
  end

  # POST /messagetolds
  # POST /messagetolds.json
  def create
    @messagetold = Messagetold.new(params[:messagetold])

    respond_to do |format|
      if @messagetold.save
        format.html { redirect_to @messagetold, notice: 'Messagetold was successfully created.' }
        format.json { render json: @messagetold, status: :created, location: @messagetold }
      else
        format.html { render action: "new" }
        format.json { render json: @messagetold.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messagetolds/1
  # PUT /messagetolds/1.json
  def update
    @messagetold = Messagetold.find(params[:id])

    respond_to do |format|
      if @messagetold.update_attributes(params[:messagetold])
        format.html { redirect_to @messagetold, notice: 'Messagetold was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @messagetold.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messagetolds/1
  # DELETE /messagetolds/1.json
  def destroy
    @messagetold = Messagetold.find(params[:id])
    @messagetold.destroy

    respond_to do |format|
      format.html { redirect_to messagetolds_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/play_controller.rb
class PlayController < ApplicationController
  def show 
    puts "11111111111111111111111111111"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/messagetolds_helper.rb
module MessagetoldsHelper
end

app/helpers/play_helper.rb
module PlayHelper
end

app/views/blog/_comments.html.erb
<div class="row">
      <div class="span8.9 well sidebar-nav" >
            <div class="row show-grid">
    <div class="span5"><div class="alert alert-success">
                  <li><a href="#"><p>掳主回</p></a><p id="comment1">的哈觉得回家啊很多看见啊啥的看见啊黑色的卡黑色的卡黑色的卡黑色的看见啊黑色的喀什的卡黑色的颗红色的快速的</p><small class="pull-right"><p>2008-08-25 16:16:54</p></small></li>
                  <br>
             </div></div>
  
  </div>
<div class="row show-grid">
    <div class="span4 offset4 alert alert-info"><li ><a href="#"><p>掳主回复</p></a></li>
                  <br></div>
  </div>

app/views/blog/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>汇率玩家</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Le styles -->
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
  </head>

  <body>
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
            <% @nodebolgpost.each do |node|   %>
              <li class="active"><a href="#"><%= node.title%></a></li>
              <% node.bolgposts.limit(5).all.each do |bolg|%>
                <li><a href="#" onclick="checkoutcontent(<%=bolg.id%>)"><%= bolg.title%></a></li>
              <% end %>
            <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <div class="hero-unit">
            <h1 id="blogtitle">依法打击自荐参选人大代表的不法分子</h1>
            <p id="blogcontent">
      针对当前出现的一些不法分子自荐参选人大代表的行为，各级党和政府既不能惊慌失措，甚至提出修宪、修法限制公民选举权，授人以柄的幼稚提议，更不能软弱涣散，听之任之，让这些所谓独立人士进入各级人大立法机构；既要从思想上和行动上旗帜鲜明地坚决维护党的利益，及时采取各种切实有力措施，破坏敌对势力的图谋，又要注意工作方式、方法，在现有宪法和法律许可的范围内，依法、坚决、果断地处置此类事件，防止以粗暴简单的方法损害党和政府在群众中的形象，维护宪法和法律的尊严。 
      </p>
            <div class="span1.5">
            <p><a class="btn btn-primary btn-large" id="showabout" onclick="showaboutbydiv('takeabout');">talk about &raquo;</a>
            <a class="btn btn-danger btn-large" id="hideabout" onclick="hideaboutbydiv('takeabout');"  style="display: none;">shut up &raquo;</a></p>
            </div>          
          </div>
          <%=render :partial=>"comments"%>
          <div style = "display: none;" id="takeabout">
          <form class="form-horizontal" action="/welcome/play" method=post>
            <fieldset>
              <legend>评论</legend>
              <div class="control-group">
                <label class="control-label" for="baseprice">主题</label>
                <div class="controls">
                  <input type="text" class="input-xlarge" id="baseprice">
                  <p class="help-block"></p>
                </div>
              </div>
              <div class="control-group">
                <label class="control-label" for="holdprice">内容</label>
                <div class="controls">
                  <textarea class="input-xlarge" id="holdprice" rows="6"></textarea>
                  <p class="help-block"></p>
                </div>
            </div>
    
            <div class="control-group">
              <div class="controls">
              <a class="btn btn-small btn-info" type="submit" onclick="makefun();" ><i class="icon-play icon-white"></i> 开始</a>
              </div>
             </div>
            </fieldset>
          </form>          
          </div>
      
      <hr>
      <footer>
        <p>&copy; moneyPlay</p>
      </footer>
      </hr>
    </div><!--/.fluid-container-->

  </body>
</html>

app/views/game/show.html.erb
  <div class="container blue">
    <div>
    <p>this is a game</p>
    </div>
     <div>
        <div class="span12" id="container_by" style="min-width: 400px; height: 400px; margin: 0 auto">
        </div>
     <blockquote class="pull-right">
     <p>默认为USD对JPY，如有需要可在本页的汇率查询输入想要查询的汇率（以上汇率报价为中间）</p>
        <small>数据更新默认为15秒</small>
        </blockquote>
    </div>
  <div class="span12">
  <form class="form-horizontal" action="/welcome/play" method=post>
  <fieldset>
    <legend>汇率查询</legend>
    <div class="control-group">
      <label class="control-label" for="baseprice">基础货币</label>
      <div class="controls">
        <input type="text" class="input-xlarge" id="baseprice">
        <p class="help-block"></p>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="holdprice">报价货币</label>
      <div class="controls">
        <input type="text" class="input-xlarge" id="holdprice">
        <p class="help-block"></p>
      </div>
    </div>
    
    <div class="control-group">
      <div class="controls">
      <a class="btn btn-small btn-info" type="submit" onclick="makefun();" ><i class="icon-play icon-white"></i> 开始</a>
<a class="btn btn-small btn-info" href="/welcome/play"><i class="icon-pause icon-white"></i> 暂停</a>
<a class="btn btn-small btn-info" href="/welcome/play"><i class="icon-info-sign icon-white"></i> 开始</a>
    </div>
   </div>
  </fieldset>
</form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stopricstra</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">汇率玩家</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="/welcome/play">首页</a></li>
              <!--<li><a href="/blog">关于汇率的基本了解</a></li> -->
              <!-- <li><a href="#contact">联系OOXX</a></li> -->
              <!-- <li><a href="/game/show">个人大盘</a></li> -->
              <!--<li><a href="./message/told">聊天室</a></li> -->
              <!-- <li><a href="luntan">luntan</a></li> -->
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
<%= yield %>

</body>
</html>

app/views/messagetolds/_form.html.erb
<%= form_for(@messagetold) do |f| %>
  <% if @messagetold.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@messagetold.errors.count, "error") %> prohibited this messagetold from being saved:</h2>

      <ul>
      <% @messagetold.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :msg %><br />
    <%= f.text_area :msg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messagetolds/edit.html.erb
<h1>Editing messagetold</h1>

<%= render 'form' %>

<%= link_to 'Show', @messagetold %> |
<%= link_to 'Back', messagetolds_path %>

app/views/messagetolds/index.html.erb
<h1>Listing messagetolds</h1>

<table>
  <tr>
    <th>User</th>
    <th>Msg</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messagetolds.each do |messagetold| %>
  <tr>
    <td><%= messagetold.user %></td>
    <td><%= messagetold.msg %></td>
    <td><%= link_to 'Show', messagetold %></td>
    <td><%= link_to 'Edit', edit_messagetold_path(messagetold) %></td>
    <td><%= link_to 'Destroy', messagetold, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Messagetold', new_messagetold_path %>

app/views/messagetolds/new.html.erb
<h1>New messagetold</h1>

<%= render 'form' %>

<%= link_to 'Back', messagetolds_path %>

app/views/messagetolds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @messagetold.user %>
</p>

<p>
  <b>Msg:</b>
  <%= @messagetold.msg %>
</p>


<%= link_to 'Edit', edit_messagetold_path(@messagetold) %> 
<%= link_to 'Back', messagetolds_path %>

app/views/play/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>汇率玩家</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Le styles -->
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
  </head>

  <body>

    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>Hello，Money！</h1>
        <p>
	  “外汇交易是我一生最爱的交易品种，我也因为英镑交易一夜成名。” 
                                                  --乔治.索罗斯
	</p>
        <p><a class="btn btn-primary btn-large">了解更多 &raquo;</a></p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4" id="container" style="min-width: 400px; height: 400px; margin: 0 auto">
        </div>

        <div class="span4">
          <h2>亚洲货币区</h2>
           <p>
	     《有关伟大的青年大将金正恩同志的资料》一宣传文中写道：“青年大将从三岁时候开始就学会了开枪，而且枪法也不错，今年用自动步枪每秒射出3发子弹，并接连射中了100米前的电灯和瓶子。而且向目标发射的20发子弹都命中10分圆点。除此之外，十几岁时就已经认识了古今内外的名将，不仅精通陆海空全领域，几天内还完成了连技术人员也很难开发的‘礼炮自动发射程式’。”<br /><br />
	     　　 这一报导还指出，金正恩精通政治、经济、文化、历史、军事等外，通过两年的留学期间完全掌握了英语、德语、法语、意大利语等四国语言，而且往后还会为了征服七国语言抽时间用工学习。除此以外，三岁时还能用毛笔书写汉语诗句，进而让周围的人赞叹不已，而且朝鲜开发核也是因为金正恩在海外留学时领悟到了“对抗核持有国家的唯一方法就是核。”
	   </p>
          <p><a class="btn" href="#">了解更多 &raquo;</a></p>
       </div>
        <div class="span4">
          <h2>欧洲货币区域</h2>
          <p>
	    齐奥塞斯库，卡尔波特，卡扎菲，萨达姆，穆巴拉克....都是中国人民的老朋友，生的伟大，死得憋屈！叹兮！<br /><br />
	    胡主席，金主席，卡斯特罗，查维斯，内贾德们，世界人民就靠你们来解放全人类了！
	  </p>
          <p><a class="btn" href="#">了解更多 &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; 金融玩家 2012</p>
      </footer>
  </body>
</html>